[tool.poetry]
name = "ftrack-framework-photoshop"
version = "1.0.0rc1"
description='ftrack Adobe Photoshop integration'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_framework_photoshop", from = "source"}]
license = "Apache-2.0"
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/integrations"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">= 3.7, < 3.8"
ftrack-python-api = ">= 1, < 3"
#ftrack
ftrack-constants = { version = ">= 2, < 3", optional = true }
ftrack-utils = { version = ">= 2, < 3", optional = true }
# framework dependencies
ftrack-framework-core = { version = ">= 2, < 3", optional = true }
# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
# extensions
ftrack-framework-common-engines = { version = ">= 2, < 3", optional = true }
ftrack-framework-common-plugins = { version = ">= 2, < 3", optional = true }
ftrack-framework-common-schemas = { version = ">= 2, < 3", optional = true }
ftrack-framework-common-tool-configs = { version = ">= 2, < 3", optional = true }
ftrack-framework-common-widgets = { version = ">= 2, < 3", optional = true }
## Photoshop Extensions
ftrack-framework-photoshop-bootstrap = { version = ">= 2, < 3", optional = true }
ftrack-framework-photoshop-hook = { version = ">= 2, < 3", optional = true }

[tool.poetry.extras]
ftrack-libs = ["ftrack-constants", "ftrack-utils"]
framework-libs = ["ftrack-framework-core"]
common-extensions = ["ftrack-framework-common-engines", "ftrack-framework-common-plugins", "ftrack-framework-common-schemas", "ftrack-framework-common-tool-configs", "ftrack-framework-common-widgets"]
photoshop-extensions = ["ftrack-framework-photoshop-bootstrap", "ftrack-framework-photoshop-hook"]

[tool.poetry.group.documentation]
optional = true

[tool.poetry.group.documentation.dependencies]
markdown = "<=3.2.2"

[tool.black]
line-length = 79
skip-string-normalization = true

