[tool.poetry]
name = "ftrack-common-engines-extension"
version = "2.0.0rc1"
description='ftrack common enignes extension'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_framework_common_engines", from = "source"}]
license = "Apache-2.0"
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/integrations"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">= 3.7, < 3.8"
#ftrack
ftrack-constants= { version = "2.0.0rc1", optional = true }
ftrack-utils = { version = "2.0.0rc2", optional = true }
# framework dependencies
ftrack-framework-engine = { version = "2.0.0rc1", optional = true }

[tool.poetry.extras]
ftrack-libs = ["ftrack-constants", "ftrack-utils"]
framework-libs = ["ftrack-framework-engine"]

[tool.black]
line-length = 79
skip-string-normalization = true
