[tool.poetry]
name = "ftrack-nuke-studio"
version = "2.5.1"
description='ftrack Connect integration with Nuke Studio'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_nuke_studio", from = "source"}]
license = "Apache-2.0"
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/integrations/projects/nuke-studio"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">= 3, < 4.0"
ftrack-python-api = ">=2,<3"
clique = '1.6.1'
appdirs = '1.4.0'
lucidity = '>= 1.5, < 2'
opentimelineio = '0.11.*'
Qt.py = ">=1.0.0, < 2"
ftrack-utils = "> 1, < 3"

[tool.poetry.group.documentation.dependencies]
PySide2 = ">=5, <6"
"Qt.py" = ">=1.0.0, < 2"
pyScss = ">= 1.2.0, < 2"
sphinx = ">= 1.8.5, < 4"
jinj2 = ">=3, <=3.0.3"
sphinx_rtd_theme = ">= 0.1.6, < 1"
lowdown = ">= 0.1.0, < 1"


